### PR TITLE
chore: dbt 0.21.0 version upgrade

### PR DESCRIPTION
**Pull request by jazibhumayun**
**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc.

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by brianhw** [comment]
Weird test failure in loading dependencies...

**Comment by jazibhumayun** [comment]
> Weird test failure in loading dependencies...

I think its because of different python versions in CI and difference python versions can give dependencies version conflicts and also I attempted to remove the pinned versions to see if version conflicts are resolved.  [requirements/constraints.txt](https://github.com/edx/dbt-schema-builder/pull/52/files#diff-86d5fe588ff2fc7dccb1f4cdd8019d4473146536e88d7a9ede946ea962a91acbL8-R15)

I generated the these dependency files using pyhon 3.7 as Jenkins schema builder job uses python 3.7 virtual env

**Comment by jazibhumayun** [comment]
As per this [BOM-2932: Replace Travis with GitHub CI
](https://github.com/edx/dbt-schema-builder/pull/50) PR's [comment](https://github.com/edx/dbt-schema-builder/pull/50#issuecomment-970238112) we are dropping python 3.6 support in GitHub Actions CI. I would recommend to generate dependency files using python 3.8, have CI tests for python 3.8 and start using python 3.8 in [Jenkins schema builder job](http://jenkins-new.analytics.edx.org/job/snowflake-schema-builder/)

**Comment by brianhw** [comment]
I agree that moving to Python 3.8 would be a reasonable thing -- but is it available on our Jenkins?  I thought we went to 3.7 because we didn't have 3.8 as an option....

**Comment by jazibhumayun** [comment]
Renamed branch name, link for new PR: [https://github.com/edx/dbt-schema-builder/pull/53](https://github.com/edx/dbt-schema-builder/pull/53)

**Pull request closed without merging**
