### PR TITLE
Estute/replace travis with GitHub ci

### PR DESCRIPTION
**Pull request by estute**
**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc.

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by pwnage101** [comment]
I would like us to continue testing multiple versions of python (especially now that python 3.9 stable has been released for many months).  In order to facilitate that, I think we need to do two things:

1. Split out quality and docs into their own github actions "jobs" so that they appear as distinct test results in the github UI that are not tied to any python version.
1. Switch to using tox-gh-actions.  Here is a live example where we have used that:
    * https://github.com/edx/analytics-tools/blob/94a5922/.github/workflows/ci.yml
    * https://github.com/edx/analytics-tools/blob/94a5922/snowflake/tox.ini

**Review by pwnage101 — CHANGES_REQUESTED** [review]
see previous comment

**Review by adzuci — APPROVED** [review]

**Comment by adzuci** [comment]
I was just looking through https://app.travis-ci.com/github/edx at remaining CI jobs and noticed this repo was still using travis.  Anything SRE can do to help land this PR?

**Comment by thomty** [comment]
Getting reminded for this daily. I believe this should be closed as stale at this point.

**Comment by openedx-webhooks** [comment]
Thanks for your pull request, but this repo does not accept outside contributions unless they are under contract. If you think this is an error, please contact @nedbat.

**Comment by openedx-webhooks** [comment]
Thanks for your pull request, but this repo does not accept outside contributions unless they are under contract. If you think this is an error, please contact @nedbat.

**Pull request closed without merging**
