### PR TITLE
Dnuzz/update to dbt 1 5

### PR DESCRIPTION
**Pull request by dnuzz**
**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc.

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by HassanJaveed84** [comment]
I don't remember the version being used in warehouse transforms, but that also should be updated to match this.

**Comment by abdulrafey38** [comment]
> I don't remember the version being used in warehouse transforms, but that also should be updated to match this.

we are using 1.3 right now in warehouse
here is the PR for matching the version https://github.com/edx/warehouse-transforms/pull/4250

**Comment by dnuzz** [comment]
Ah I thought the version was pinned, but I found the DSL and you are correct it always goes to latest. I might suggest that we pin the version [here](https://github.com/edx/jenkins-job-dsl/blob/edde176415470831393012bb1f6a33bd19c9cd23/dataeng/resources/snowflake-schema-builder.sh#L11) to the current version before we go doing the upgrade. I could see things taking a while to properly upgrade and test. Might as well buy ourselves a little time?

**Comment by abdulrafey38** [comment]
> Ah I thought the version was pinned, but I found the DSL and you are correct it always goes to latest. I might suggest that we pin the version [here](https://github.com/edx/jenkins-job-dsl/blob/edde176415470831393012bb1f6a33bd19c9cd23/dataeng/resources/snowflake-schema-builder.sh#L11) to the current version before we go doing the upgrade. I could see things taking a while to properly upgrade and test. Might as well buy ourselves a little time?

@dnuzz so we need to pin 0.4.11 ==>  [here](https://github.com/edx/jenkins-job-dsl/blob/edde176415470831393012bb1f6a33bd19c9cd23/dataeng/resources/snowflake-schema-builder.sh#L11) right? because after upgrade the latest version will be 0.5.0

**Comment by dnuzz** [comment]
@abdulrafey38 correct pin it there to that version. We can unpin later if we also want to upgrade that

**Comment by abdulrafey38** [comment]
> 0.4.11

https://github.com/edx/jenkins-job-dsl/pull/1662

**Pull request merged**
